/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Codegraphy API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
  ApiRoot,
  BodySaveCellContentsApiCellsCellIdPut,
  CellContent,
  GraphModelInput,
  GraphModelOutput,
  HTTPValidationError,
  ReadCellContentsApiCellsCellIdGetParams,
  ReadGraphApiGraphsGetParams,
  RunCellApiCellsCellIdRunPatchParams,
  SaveCellContentsApiCellsCellIdPutParams,
  UpdateGraphApiGraphsPutParams,
} from './schema';

/**
 * @summary Read Root
 */
export const readRootApiGet = (options?: AxiosRequestConfig): Promise<AxiosResponse<ApiRoot>> => {
  return axios.default.get(`http://127.0.0.1:8000/api/`, options);
};

export const getReadRootApiGetQueryKey = () => {
  return [`http://127.0.0.1:8000/api/`] as const;
};

export const getReadRootApiGetQueryOptions = <
  TData = Awaited<ReturnType<typeof readRootApiGet>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof readRootApiGet>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getReadRootApiGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof readRootApiGet>>> = ({ signal }) =>
    readRootApiGet({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof readRootApiGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ReadRootApiGetQueryResult = NonNullable<Awaited<ReturnType<typeof readRootApiGet>>>;
export type ReadRootApiGetQueryError = AxiosError<unknown>;

/**
 * @summary Read Root
 */
export const useReadRootApiGet = <
  TData = Awaited<ReturnType<typeof readRootApiGet>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof readRootApiGet>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getReadRootApiGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Read Graph
 */
export const readGraphApiGraphsGet = (
  params: ReadGraphApiGraphsGetParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GraphModelOutput>> => {
  return axios.default.get(`http://127.0.0.1:8000/api/graphs/`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getReadGraphApiGraphsGetQueryKey = (params: ReadGraphApiGraphsGetParams) => {
  return [`http://127.0.0.1:8000/api/graphs/`, ...(params ? [params] : [])] as const;
};

export const getReadGraphApiGraphsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof readGraphApiGraphsGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: ReadGraphApiGraphsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof readGraphApiGraphsGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getReadGraphApiGraphsGetQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof readGraphApiGraphsGet>>> = ({ signal }) =>
    readGraphApiGraphsGet(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof readGraphApiGraphsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ReadGraphApiGraphsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof readGraphApiGraphsGet>>
>;
export type ReadGraphApiGraphsGetQueryError = AxiosError<HTTPValidationError>;

/**
 * @summary Read Graph
 */
export const useReadGraphApiGraphsGet = <
  TData = Awaited<ReturnType<typeof readGraphApiGraphsGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: ReadGraphApiGraphsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof readGraphApiGraphsGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getReadGraphApiGraphsGetQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Update Graph
 */
export const updateGraphApiGraphsPut = (
  graphModelInput: GraphModelInput,
  params: UpdateGraphApiGraphsPutParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GraphModelOutput>> => {
  return axios.default.put(`http://127.0.0.1:8000/api/graphs/`, graphModelInput, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getUpdateGraphApiGraphsPutMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateGraphApiGraphsPut>>,
    TError,
    { data: GraphModelInput; params: UpdateGraphApiGraphsPutParams },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateGraphApiGraphsPut>>,
  TError,
  { data: GraphModelInput; params: UpdateGraphApiGraphsPutParams },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateGraphApiGraphsPut>>,
    { data: GraphModelInput; params: UpdateGraphApiGraphsPutParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return updateGraphApiGraphsPut(data, params, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateGraphApiGraphsPutMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateGraphApiGraphsPut>>
>;
export type UpdateGraphApiGraphsPutMutationBody = GraphModelInput;
export type UpdateGraphApiGraphsPutMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Update Graph
 */
export const useUpdateGraphApiGraphsPut = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateGraphApiGraphsPut>>,
    TError,
    { data: GraphModelInput; params: UpdateGraphApiGraphsPutParams },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getUpdateGraphApiGraphsPutMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Read Cell Contents
 */
export const readCellContentsApiCellsCellIdGet = (
  cellId: string,
  params: ReadCellContentsApiCellsCellIdGetParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<CellContent>> => {
  return axios.default.get(`http://127.0.0.1:8000/api/cells/${cellId}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getReadCellContentsApiCellsCellIdGetQueryKey = (
  cellId: string,
  params: ReadCellContentsApiCellsCellIdGetParams,
) => {
  return [`http://127.0.0.1:8000/api/cells/${cellId}`, ...(params ? [params] : [])] as const;
};

export const getReadCellContentsApiCellsCellIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof readCellContentsApiCellsCellIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  cellId: string,
  params: ReadCellContentsApiCellsCellIdGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof readCellContentsApiCellsCellIdGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getReadCellContentsApiCellsCellIdGetQueryKey(cellId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof readCellContentsApiCellsCellIdGet>>> = ({
    signal,
  }) => readCellContentsApiCellsCellIdGet(cellId, params, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!cellId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof readCellContentsApiCellsCellIdGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ReadCellContentsApiCellsCellIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof readCellContentsApiCellsCellIdGet>>
>;
export type ReadCellContentsApiCellsCellIdGetQueryError = AxiosError<HTTPValidationError>;

/**
 * @summary Read Cell Contents
 */
export const useReadCellContentsApiCellsCellIdGet = <
  TData = Awaited<ReturnType<typeof readCellContentsApiCellsCellIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  cellId: string,
  params: ReadCellContentsApiCellsCellIdGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof readCellContentsApiCellsCellIdGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getReadCellContentsApiCellsCellIdGetQueryOptions(cellId, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Save Cell Contents
 */
export const saveCellContentsApiCellsCellIdPut = (
  cellId: string,
  bodySaveCellContentsApiCellsCellIdPut: BodySaveCellContentsApiCellsCellIdPut,
  params: SaveCellContentsApiCellsCellIdPutParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GraphModelOutput>> => {
  return axios.default.put(
    `http://127.0.0.1:8000/api/cells/${cellId}`,
    bodySaveCellContentsApiCellsCellIdPut,
    {
      ...options,
      params: { ...params, ...options?.params },
    },
  );
};

export const getSaveCellContentsApiCellsCellIdPutMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof saveCellContentsApiCellsCellIdPut>>,
    TError,
    {
      cellId: string;
      data: BodySaveCellContentsApiCellsCellIdPut;
      params: SaveCellContentsApiCellsCellIdPutParams;
    },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof saveCellContentsApiCellsCellIdPut>>,
  TError,
  {
    cellId: string;
    data: BodySaveCellContentsApiCellsCellIdPut;
    params: SaveCellContentsApiCellsCellIdPutParams;
  },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof saveCellContentsApiCellsCellIdPut>>,
    {
      cellId: string;
      data: BodySaveCellContentsApiCellsCellIdPut;
      params: SaveCellContentsApiCellsCellIdPutParams;
    }
  > = (props) => {
    const { cellId, data, params } = props ?? {};

    return saveCellContentsApiCellsCellIdPut(cellId, data, params, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SaveCellContentsApiCellsCellIdPutMutationResult = NonNullable<
  Awaited<ReturnType<typeof saveCellContentsApiCellsCellIdPut>>
>;
export type SaveCellContentsApiCellsCellIdPutMutationBody = BodySaveCellContentsApiCellsCellIdPut;
export type SaveCellContentsApiCellsCellIdPutMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Save Cell Contents
 */
export const useSaveCellContentsApiCellsCellIdPut = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof saveCellContentsApiCellsCellIdPut>>,
    TError,
    {
      cellId: string;
      data: BodySaveCellContentsApiCellsCellIdPut;
      params: SaveCellContentsApiCellsCellIdPutParams;
    },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getSaveCellContentsApiCellsCellIdPutMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Run Cell
 */
export const runCellApiCellsCellIdRunPatch = (
  cellId: string,
  params: RunCellApiCellsCellIdRunPatchParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GraphModelOutput>> => {
  return axios.default.patch(`http://127.0.0.1:8000/api/cells/${cellId}/run`, undefined, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getRunCellApiCellsCellIdRunPatchMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runCellApiCellsCellIdRunPatch>>,
    TError,
    { cellId: string; params: RunCellApiCellsCellIdRunPatchParams },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof runCellApiCellsCellIdRunPatch>>,
  TError,
  { cellId: string; params: RunCellApiCellsCellIdRunPatchParams },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof runCellApiCellsCellIdRunPatch>>,
    { cellId: string; params: RunCellApiCellsCellIdRunPatchParams }
  > = (props) => {
    const { cellId, params } = props ?? {};

    return runCellApiCellsCellIdRunPatch(cellId, params, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RunCellApiCellsCellIdRunPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof runCellApiCellsCellIdRunPatch>>
>;

export type RunCellApiCellsCellIdRunPatchMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Run Cell
 */
export const useRunCellApiCellsCellIdRunPatch = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runCellApiCellsCellIdRunPatch>>,
    TError,
    { cellId: string; params: RunCellApiCellsCellIdRunPatchParams },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getRunCellApiCellsCellIdRunPatchMutationOptions(options);

  return useMutation(mutationOptions);
};
