/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Codegraphy API
 * OpenAPI spec version: 0.1.0
 */
import type { CodeCellModelExecutionTime } from './codeCellModelExecutionTime';
import type { CodeCellModelParamsItem } from './codeCellModelParamsItem';
import type { CellPosition } from './cellPosition';
import type { CodeCellModelReturnsItem } from './codeCellModelReturnsItem';

export interface CodeCellModel {
  cell_type: 'code';
  execution_count: number;
  execution_time: CodeCellModelExecutionTime;
  file_name: string;
  id: string;
  kernel: string;
  outputs: string[];
  params: CodeCellModelParamsItem[];
  position: CellPosition;
  returns: CodeCellModelReturnsItem[];
}
