/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CodeCellModel } from './codeCellModel';
import type { InputCellModel } from './inputCellModel';

export type GraphModelInputCellsItem = CodeCellModel | InputCellModel;
