/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GraphModelInputCellsItem } from './graphModelInputCellsItem';
import type { LinkModel } from './linkModel';
import type { MetadataModel } from './metadataModel';

export interface GraphModelInput {
  cells: GraphModelInputCellsItem[];
  links: LinkModel[];
  metadata: MetadataModel;
}
