/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GraphModelCellsItem } from './graphModelCellsItem';
import type { LinkModel } from './linkModel';
import type { MetadataModel } from './metadataModel';

export interface GraphModel {
  cells: GraphModelCellsItem[];
  links: LinkModel[];
  metadata: MetadataModel;
}
