/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Codegraphy API
 * OpenAPI spec version: 0.1.0
 */
import type { GraphModelOutputCellsItem } from './graphModelOutputCellsItem';
import type { LinkModel } from './linkModel';
import type { MetadataModel } from './metadataModel';

export interface GraphModelOutput {
  cells: GraphModelOutputCellsItem[];
  links: LinkModel[];
  metadata: MetadataModel;
}
