/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Codegraphy API
 * OpenAPI spec version: 0.1.0
 */

export type InputCellModelType = (typeof InputCellModelType)[keyof typeof InputCellModelType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InputCellModelType = {
  text: 'text',
  number: 'number',
  email: 'email',
} as const;
