/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface KernelModel {
  display_name: string;
  language: string;
  name: string;
}
