/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LinkItemModel } from './linkItemModel';

export interface LinkModel {
  from_cell: LinkItemModel;
  to_cell: LinkItemModel;
}
