/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Codegraphy API
 * OpenAPI spec version: 0.1.0
 */
import type { LinkItemModel } from './linkItemModel';
import type { LinkModelValue } from './linkModelValue';

export interface LinkModel {
  from_cell: LinkItemModel;
  to_cell: LinkItemModel;
  value: LinkModelValue;
}
