/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LinkItemModelPort } from './linkItemModelPort';

export interface LinkItemModel {
  id: string;
  port: LinkItemModelPort;
}
