/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Codegraphy API
 * OpenAPI spec version: 0.1.0
 */
import type { KernelModel } from './kernelModel';

export interface MetadataModel {
  graph_version: number;
  graph_version_minor: number;
  kernels: KernelModel[];
}
